<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Discord.Net.targets" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <IsAotCompatible>false</IsAotCompatible>
    <RootNamespace>Discord</RootNamespace>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CA2252</NoWarn>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MorseCode.ITask" Version="2.0.3" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Interactive.Async" Version="6.0.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sourcegen\Discord.Net.Hanz\Discord.Net.Hanz.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    <ProjectReference Include="..\Discord.Net.Models\Discord.Net.Models.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
  </ItemGroup>

</Project>
