<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Discord</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Discord.Net.Core\Discord.Net.Core.csproj" />
    </ItemGroup>

</Project>
