<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Discord.Net.targets" />
  <Import Project="../../StyleAnalyzer.targets" />
  <PropertyGroup>
    <AssemblyName>Discord.Net.Core</AssemblyName>
    <RootNamespace>Discord</RootNamespace>
    <Description>The core components for the Discord.Net library.</Description>
    <TargetFrameworks>net9.0;net8.0;</TargetFrameworks>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <IsTrimmable>false</IsTrimmable>
    <IsAotCompatible>false</IsAotCompatible>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Interactive.Async" Version="6.0.1" />
    <PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>