<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Discord.Net.targets" />
  <Import Project="../../StyleAnalyzer.targets" />
  <PropertyGroup>
    <AssemblyName>Discord.Net.WebSocket</AssemblyName>
    <RootNamespace>Discord.WebSocket</RootNamespace>
    <Description>A core Discord.Net library containing the WebSocket client and models.</Description>
    <TargetFrameworks>net10.0;net9.0;net8.0;</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <IsTrimmable>false</IsTrimmable>
    <IsAotCompatible>false</IsAotCompatible>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\tools\Discord.Net.Dave\Discord.Net.Dave.csproj" />
    <ProjectReference Include="..\Discord.Net.Core\Discord.Net.Core.csproj" />
    <ProjectReference Include="..\Discord.Net.Rest\Discord.Net.Rest.csproj" />
  </ItemGroup>
</Project>
