name: Deploy Docs

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "dev" ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup DocFX
      run: dotnet tool install -g docfx --version 2.71.0
        
    - name: Auth DNet bot
      id: bot_auth
      uses: machine-learning-apps/actions-app-token@master
      with:
        APP_PEM: ${{ secrets.DNET_BOT_PEM }}
        APP_ID: ${{ secrets.DNET_BOT_ID }}

    - name: Build DNet docs
      run: docfx docs/docfx.json

    - name: Create Output Directory
      run: mkdir output | mkdir output/latest | cp -a docs/_site/. output/latest/.

    - name: Push to static docs
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ steps.bot_auth.outputs.app_token }}
      with:
        source-directory: '~/output'
        destination-github-username: 'discord-net'
        destination-repository-name: 'docs-static'
        user-email: dnetbot@discordnet.dev
        target-branch: master
